/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bibliotheque;

/**
 *
 * @author Kalala
 */
import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        afficherLivres();
    }

    public void afficherLivres() {
    // 1. On définit les colonnes de notre tableau
    String[] colonnes = {"ID", "Titre", "Auteur", "Catégorie", "Disponible"};
    DefaultTableModel modele = new DefaultTableModel(null, colonnes);
    
    try {
        Connection con = DatabaseConnection.seConnecter();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM livres");
        
        // 2. On parcourt les résultats de la base de données
        while (rs.next()) {
            Object[] ligne = {
                rs.getInt("id_livre"),
                rs.getString("titre"),
                rs.getString("auteur"),
                rs.getString("categorie"),
                rs.getBoolean("disponible") ? "Oui" : "Sorti"
            };
            modele.addRow(ligne); // On ajoute la ligne au modèle
        }
        
        // 3. On applique le modèle au tableau visuel
        tableLivres.setModel(modele);
        
    } catch (Exception e) {
        System.out.println("Erreur d'affichage : " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivres = new javax.swing.JTable();
        txtTitre = new javax.swing.JTextField();
        txtAuteur = new javax.swing.JTextField();
        txtCategorie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableLivres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Titre", "Auteur", "Disponibilité"
            }
        ));
        tableLivres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLivresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLivres);

        txtAuteur.addActionListener(this::txtAuteurActionPerformed);

        jLabel1.setText("Titre");

        jLabel2.setText("Auteur");

        jLabel3.setText("Categorie");

        btnAjouter.setBackground(new java.awt.Color(0, 204, 0));
        btnAjouter.setText("Ajouter le livre");
        btnAjouter.addActionListener(this::btnAjouterActionPerformed);

        btnSupprimer.setBackground(new java.awt.Color(255, 0, 0));
        btnSupprimer.setText("Supprimer le livre");
        btnSupprimer.addActionListener(this::btnSupprimerActionPerformed);

        btnModifier.setBackground(new java.awt.Color(255, 255, 0));
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(this::btnModifierActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTitre)
                    .addComponent(txtAuteur)
                    .addComponent(txtCategorie)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(txtAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(txtCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifier))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestion des Livres", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lecteurs", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registre des Emprunts", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAuteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuteurActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // 1. Récupérer le texte tapé par l'administrateur
        String titre = txtTitre.getText();
        String auteur = txtAuteur.getText();
        String categorie = txtCategorie.getText();

        // 2. Petite sécurité : vérifier que le titre n'est pas vide
        if (titre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le titre du livre est obligatoire !", "Erreur", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // On arrête l'exécution ici si c'est vide
        }

        // 3. Connexion et envoi à la base de données
        try {
            // On appelle notre classe de connexion (Vérifie que le nom correspond bien à ta classe de l'étape 3)
            java.sql.Connection con = DatabaseConnection.seConnecter();

            // On prépare la requête SQL (les "?" sont là pour des raisons de sécurité)
            String sql = "INSERT INTO livres (titre, auteur, categorie) VALUES (?, ?, ?)";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);

            // On remplace les "?" par les vraies valeurs
            pst.setString(1, titre);
            pst.setString(2, auteur);
            pst.setString(3, categorie);

            // On exécute la requête
            pst.executeUpdate();

            // On affiche un petit message de succès à l'écran
            javax.swing.JOptionPane.showMessageDialog(this, "Le livre a été ajouté avec succès !");
            
            afficherLivres();

            // On vide les champs de texte pour le prochain livre
            txtTitre.setText("");
            txtAuteur.setText("");
            txtCategorie.setText("");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout : " + e.getMessage(), "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
    // 1. Vérifier si une ligne est sélectionnée dans le tableau
    int ligneSelectionnee = tableLivres.getSelectedRow();

    if (ligneSelectionnee == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Veuillez sélectionner un livre dans le tableau !");
        return;
    }

    // 2. Récupérer l'ID du livre (colonne 0 de la ligne sélectionnée)
    String id = tableLivres.getValueAt(ligneSelectionnee, 0).toString();

    // 3. Demander confirmation (sécurité pour l'administrateur)
    int confirmation = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Voulez-vous vraiment supprimer ce livre ?", "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirmation == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection con = DatabaseConnection.seConnecter();
            String sql = "DELETE FROM livres WHERE id_livre = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, id);
            pst.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this, "Livre supprimé !");

            // 4. Rafraîchir le tableau automatiquement
            afficherLivres();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage());
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void tableLivresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLivresMouseClicked
        int ligne = tableLivres.getSelectedRow();
        txtTitre.setText(tableLivres.getValueAt(ligne, 1).toString());
        txtAuteur.setText(tableLivres.getValueAt(ligne, 2).toString());
        txtCategorie.setText(tableLivres.getValueAt(ligne, 3).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tableLivresMouseClicked

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        int ligne = tableLivres.getSelectedRow();
        if (ligne == -1) return;

        String id = tableLivres.getValueAt(ligne, 0).toString();

        try {
            java.sql.Connection con = DatabaseConnection.seConnecter();
            String sql = "UPDATE livres SET titre=?, auteur=?, categorie=? WHERE id_livre=?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtTitre.getText());
            pst.setString(2, txtAuteur.getText());
            pst.setString(3, txtCategorie.getText());
            pst.setString(4, id);

            pst.executeUpdate();
            afficherLivres(); // Rafraîchir
            javax.swing.JOptionPane.showMessageDialog(this, "Mise à jour réussie !");
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableLivres;
    private javax.swing.JTextField txtAuteur;
    private javax.swing.JTextField txtCategorie;
    private javax.swing.JTextField txtTitre;
    // End of variables declaration//GEN-END:variables
}
